In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(color_codes = True)
import time, warnings
warnings.filterwarnings("ignore")

In [2]:
flights = pd.read_csv("D:\\Project\\flights.csv")
flights.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
flights.tail()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
5819074,2015,12,31,4,B6,688,N657JB,LAX,BOS,2359,...,753.0,-26.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819075,2015,12,31,4,B6,745,N828JB,JFK,PSE,2359,...,430.0,-16.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819076,2015,12,31,4,B6,1503,N913JB,JFK,SJU,2359,...,432.0,-8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819077,2015,12,31,4,B6,333,N527JB,MCO,SJU,2359,...,330.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819078,2015,12,31,4,B6,839,N534JB,JFK,BQN,2359,...,442.0,2.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
flights.columns, flights.shape

(Index(['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'FLIGHT_NUMBER',
        'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
        'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'TAXI_OUT',
        'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
        'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME',
        'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON',
        'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY',
        'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY'],
       dtype='object'),
 (5819079, 31))

In [5]:
flights.dtypes

YEAR                     int64
MONTH                    int64
DAY                      int64
DAY_OF_WEEK              int64
AIRLINE                 object
FLIGHT_NUMBER            int64
TAIL_NUMBER             object
ORIGIN_AIRPORT          object
DESTINATION_AIRPORT     object
SCHEDULED_DEPARTURE      int64
DEPARTURE_TIME         float64
DEPARTURE_DELAY        float64
TAXI_OUT               float64
WHEELS_OFF             float64
SCHEDULED_TIME         float64
ELAPSED_TIME           float64
AIR_TIME               float64
DISTANCE                 int64
WHEELS_ON              float64
TAXI_IN                float64
SCHEDULED_ARRIVAL        int64
ARRIVAL_TIME           float64
ARRIVAL_DELAY          float64
DIVERTED                 int64
CANCELLED                int64
CANCELLATION_REASON     object
AIR_SYSTEM_DELAY       float64
SECURITY_DELAY         float64
AIRLINE_DELAY          float64
LATE_AIRCRAFT_DELAY    float64
WEATHER_DELAY          float64
dtype: object

In [6]:
flights.describe()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
count,5819079.0,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.732926e+06,5.732926e+06,5.730032e+06,5.730032e+06,...,5.819079e+06,5.726566e+06,5.714008e+06,5.819079e+06,5.819079e+06,1.063439e+06,1.063439e+06,1.063439e+06,1.063439e+06,1.063439e+06
mean,2015.0,6.524085e+00,1.570459e+01,3.926941e+00,2.173093e+03,1.329602e+03,1.335204e+03,9.370158e+00,1.607166e+01,1.357171e+03,...,1.493808e+03,1.476491e+03,4.407057e+00,2.609863e-03,1.544643e-02,1.348057e+01,7.615387e-02,1.896955e+01,2.347284e+01,2.915290e+00
std,0.0,3.405137e+00,8.783425e+00,1.988845e+00,1.757064e+03,4.837518e+02,4.964233e+02,3.708094e+01,8.895574e+00,4.980094e+02,...,5.071647e+02,5.263197e+02,3.927130e+01,5.102012e-02,1.233201e-01,2.800368e+01,2.143460e+00,4.816164e+01,4.319702e+01,2.043334e+01
min,2015.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-8.200000e+01,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,-8.700000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2015.0,4.000000e+00,8.000000e+00,2.000000e+00,7.300000e+02,9.170000e+02,9.210000e+02,-5.000000e+00,1.100000e+01,9.350000e+02,...,1.110000e+03,1.059000e+03,-1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2015.0,7.000000e+00,1.600000e+01,4.000000e+00,1.690000e+03,1.325000e+03,1.330000e+03,-2.000000e+00,1.400000e+01,1.343000e+03,...,1.520000e+03,1.512000e+03,-5.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,3.000000e+00,0.000000e+00
75%,2015.0,9.000000e+00,2.300000e+01,6.000000e+00,3.230000e+03,1.730000e+03,1.740000e+03,7.000000e+00,1.900000e+01,1.754000e+03,...,1.918000e+03,1.917000e+03,8.000000e+00,0.000000e+00,0.000000e+00,1.800000e+01,0.000000e+00,1.900000e+01,2.900000e+01,0.000000e+00
max,2015.0,1.200000e+01,3.100000e+01,7.000000e+00,9.855000e+03,2.359000e+03,2.400000e+03,1.988000e+03,2.250000e+02,2.400000e+03,...,2.400000e+03,2.400000e+03,1.971000e+03,1.000000e+00,1.000000e+00,1.134000e+03,5.730000e+02,1.971000e+03,1.331000e+03,1.211000e+03

In [7]:
corrmat = flights.corr()
corrmat

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
YEAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MONTH,NaN,1.000000,0.008874,-0.007847,-0.020746,0.000207,-0.004085,-0.021994,-0.013117,-0.004946,...,-0.010121,-0.009133,-0.036793,-0.000991,-0.055043,-0.002214,0.007925,0.011262,0.004839,-0.008682
DAY,NaN,0.008874,1.000000,0.001111,0.001855,-0.001647,-0.002644,-0.000176,-0.002661,-0.003318,...,-0.003688,-0.004310,-0.003097,0.001981,-0.003537,-0.007375,-0.000510,0.006728,0.008869,0.008882
DAY_OF_WEEK,NaN,-0.007847,0.001111,1.000000,0.014461,0.008007,0.005607,-0.011510,-0.020639,0.004060,...,0.007092,0.005641,-0.017027,-0.001442,-0.022230,-0.023674,0.001576,0.011264,-0.018026,-0.006794
FLIGHT_NUMBER,NaN,-0.020746,0.001855,0.014461,1.000000,-0.005485,-0.001444,-0.008665,0.050369,0.005289,...,-0.013947,-0.002821,0.018419,0.003802,0.037895,-0.009235,-0.007994,0.007168,0.022274,-0.002836
SCHEDULED_DEPARTURE,NaN,0.000207,-0.001647,0.008007,-0.005485,1.000000,0.963791,0.110149,0.006581,0.938008,...,0.706237,0.629342,0.100220,-0.000752,0.011752,-0.075174,-0.005068,-0.089095,0.145054,-0.013470
DEPARTURE_TIME,NaN,-0.004085,-0.002644,0.005607,-0.001444,0.963791,1.000000,0.171723,0.014002,0.971971,...,0.710223,0.648265,0.159787,0.001425,0.008055,-0.043878,-0.004682,-0.024131,0.182374,-0.004221
DEPARTURE_DELAY,NaN,-0.021994,-0.000176,-0.011510,-0.008665,0.110149,0.171723,1.000000,0.058515,0.162582,...,0.097566,0.049236,0.944672,0.022963,0.033099,0.095917,0.011877,0.621296,0.554802,0.243532
TAXI_OUT,NaN,-0.013117,-0.002661,-0.020639,0.050369,0.006581,0.014002,0.058515,1.000000,0.039104,...,0.024384,0.029745,0.227319,0.012251,0.005062,0.361659,-0.005988,-0.070290,-0.127824,0.063308
WHEELS_OFF,NaN,-0.004946,-0.003318,0.004060,0.005289,0.938008,0.971971,0.162582,0.039104,1.000000,...,0.721877,0.667991,0.155773,0.001667,0.004805,-0.026377,-0.006180,-0.032810,0.156089,-0.008338
SCHEDULED_TIME,NaN,0.010784,0.003403,0.014954,-0.317394,-0.016609,-0.020851,0.027799,0.112302,-0.028289,...,0.031963,0.020439,-0.030029,0.014012,-0.027827,0.030445,0.007085,0.033051,-0.044554,-0.001624
ELAPSED_TIME,NaN,0.001871,0.001419,0.011510,-0.306611,-0.017935,-0.021990,0.030805,0.205195,-0.027133,...,0.031246,0.022579,0.029120,NaN,NaN,0.151510,0.004588,-0.001619,-0.091822,0.006735
AIR_TIME,NaN,0.003379,0.001923,0.014284,-0.319681,-0.015756,-0.021146,0.023495,0.087608,-0.029654,...,0.029698,0.019383,-0.007108,NaN,NaN,0.056492,0.006631,0.018366,-0.063624,-0.005410
DISTANCE,NaN,0.011437,0.003529,0.016516,-0.331280,-0.009572,-0.016492,0.024106,0.072333,-0.027586,...,0.027369,0.015098,-0.025444,0.012896,-0.032853,0.015040,0.007513,0.032198,-0.044569,-0.008721
WHEELS_ON,NaN,-0.008917,-0.004294,0.005642,-0.006134,0.656098,0.675882,0.058674,0.032584,0.695734,...,0.870077,0.968035,0.058880,0.006098,NaN,0.006796,-0.007728,-0.060747,-0.004738,-0.025507
TAXI_IN,NaN,0.002095,-0.001656,0.001111,-0.019740,-0.044719,-0.040613,0.012784,0.003221,-0.038814,...,-0.007444,0.002215,0.116628,0.022348,NaN,0.244565,-0.005392,-0.050092,-0.055582,-0.001531
SCHEDULED_ARRIVAL,NaN,-0.010121,-0.003688,0.007092,-0.013947,0.706237,0.710223,0.097566,0.024384,0.721877,...,1.000000,0.861931,0.088824,0.004820,0.007763,-0.028763,-0.003396,-0.073852,0.109430,-0.006694
ARRIVAL_TIME,NaN,-0.009133,-0.004310,0.005641,-0.002821,0.629342,0.648265,0.049236,0.029745,0.667991,...,0.861931,1.000000,0.049876,0.004771,NaN,0.004523,-0.007462,-0.061692,-0.012209,-0.026043
ARRIVAL_DELAY,NaN,-0.036793,-0.003097,-0.017027,0.018419,0.100220,0.159787,0.944672,0.227319,0.155773,...,0.088824,0.049876,1.000000,NaN,NaN,0.247187,0.009655,0.609351,0.522013,0.264799
DIVERTED,NaN,-0.000991,0.001981,-0.001442,0.003802,-0.000752,0.001425,0.022963,0.012251,0.001667,...,0.004820,0.004771,NaN,1.000000,-0.006407,NaN,NaN,NaN,NaN,NaN
CANCELLED,NaN,-0.055043,-0.003537,-0.022230,0.037895,0.011752,0.008055,0.033099,0.005062,0.004805,...,0.007763,NaN,NaN,-0.006407,1.000000,NaN,NaN,NaN,NaN,NaN
AIR_SYSTEM_DELAY,NaN,-0.002214,-0.007375,-0.023674,-0.009235,-0.075174,-0.043878,0.095917,0.361659,-0.026377,...,-0.028763,0.004523,0.247187,NaN,NaN,1.000000,-0.010797,-0.120141,-0.145789,-0.000728
SECURITY_DELAY,NaN,0.007925,-0.000510,0.001576,-0.007994,-0.005068,-0.004682,0.011877,-0.005988,-0.006180,...,-0.003396,-0.007462,0.009655,NaN,NaN,-0.010797,1.000000,-0.012876,-0.011615,-0.004840
AIRLINE_DELAY,NaN,0.011262,0.006728,0.011264,0.007168,-0.089095,-0.024131,0.621296,-0.070290,-0.032810,...,-0.073852,-0.061692,0.609351,NaN,NaN,-0.120141,-0.012876,1.000000,-0.106010,-0.050865
LATE_AIRCRAFT_DELAY,NaN,0.004839,0.008869,-0.018026,0.022274,0.145054,0.182374,0.554802,-0.127824,0.156089,...,0.109430,-0.012209,0.522013,NaN,NaN,-0.145789,-0.011615,-0.106010,1.000000,-0.021747
WEATHER_DELAY,NaN,-0.008682,0.008882,-0.006794,-0.002836,-0.013470,-0.004221,0.243532,0.063308,-0.008338,...,-0.006694,-0.026043,0.264799,NaN,NaN,-0.000728,-0.004840,-0.050865,-0.021747,1.000000

In [3]:
flights.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           86153
DEPARTURE_DELAY          86153
TAXI_OUT                 89047
WHEELS_OFF               89047
SCHEDULED_TIME               6
ELAPSED_TIME            105071
AIR_TIME                105071
DISTANCE                     0
WHEELS_ON                92513
TAXI_IN                  92513
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             92513
ARRIVAL_DELAY           105071
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4755640
SECURITY_DELAY         4755640
AIRLINE_DELAY          4755640
LATE_AIRCRAFT_DELAY    4755640
WEATHER_DELAY          4755640
dtype: int64

In [3]:
#numeric features
numeric_features = [feature for feature in flights.columns if flights[feature].dtypes!='O']
print(numeric_features)

['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'FLIGHT_NUMBER', 'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'TAXI_OUT', 'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME', 'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED', 'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY', 'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY']

In [4]:
flights_num = flights[numeric_features]
flights_num.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,98,5,2354.0,-11.0,21.0,15.0,...,430,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,2336,10,2.0,-8.0,12.0,14.0,...,750,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,840,20,18.0,-2.0,16.0,34.0,...,806,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,258,20,15.0,-5.0,15.0,30.0,...,805,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,135,25,24.0,-1.0,11.0,35.0,...,320,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN

In [5]:
missing_columns = flights_num.columns

def random_imputation(df, feature):

    number_missing = df[feature].isnull().sum()
    observed_values = df.loc[df[feature].notnull(), feature]
    df.loc[df[feature].isnull(), feature + '_imp'] = np.random.choice(observed_values, number_missing, replace = True)
    
    return df

In [6]:
for feature in missing_columns:
    flights_num[feature + '_imp'] = flights_num[feature]
    flights_num = random_imputation(flights_num, feature)

In [7]:
from sklearn import linear_model
from sklearn.linear_model import Ridge
# linera model-ridge
deter_data = pd.DataFrame(columns = [name for name in missing_columns])

for feature in missing_columns:
        
    deter_data[feature] = flights_num[feature + "_imp"]
    parameters = list(set(flights_num.columns) - set(missing_columns) - {feature + '_imp'})
    
    #Create a Linear Regression ridge model to estimate the missing data
    model = linear_model.Ridge()
    model.fit(X = flights_num[parameters], y = flights_num[feature + '_imp'])
    
    #preserve the index of the missing data from the original dataframe
    deter_data.loc[flights_num[feature].isnull(), feature] = model.predict(flights_num[parameters])[flights_num[feature].isnull()]

In [8]:
deter_data.head(), deter_data.shape

(     YEAR  MONTH  DAY  DAY_OF_WEEK  FLIGHT_NUMBER  SCHEDULED_DEPARTURE  \
 0  2015.0    1.0  1.0          4.0           98.0                  5.0
 1  2015.0    1.0  1.0          4.0         2336.0                 10.0
 2  2015.0    1.0  1.0          4.0          840.0                 20.0
 3  2015.0    1.0  1.0          4.0          258.0                 20.0
 4  2015.0    1.0  1.0          4.0          135.0                 25.0

    DEPARTURE_TIME  DEPARTURE_DELAY  TAXI_OUT  WHEELS_OFF  ...  \
 0          2354.0            -11.0      21.0        15.0  ...
 1             2.0             -8.0      12.0        14.0  ...
 2            18.0             -2.0      16.0        34.0  ...
 3            15.0             -5.0      15.0        30.0  ...
 4            24.0             -1.0      11.0        35.0  ...

    SCHEDULED_ARRIVAL  ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
 0              430.0         408.0          -22.0       0.0        0.0
 1              750.0         741.0           -9.0       0.0        0.0
 2              806.0         811.0            5.0       0.0        0.0
 3              805.0         756.0           -9.0       0.0        0.0
 4              320.0         259.0          -21.0       0.0        0.0

    AIR_SYSTEM_DELAY  SECURITY_DELAY  AIRLINE_DELAY  LATE_AIRCRAFT_DELAY  \
 0         14.905347        0.066836       8.451934            16.999084
 1         10.782770        0.069328      11.761628            19.791908
 2         16.790757        0.077693      18.120679            15.549624
 3         14.706302        0.093863      21.061453            19.206171
 4          3.116763        0.020278      -8.213620            24.206035

    WEATHER_DELAY
 0      -0.217266
 1       1.310263
 2       2.491187
 3       2.814779
 4      -1.014899

 [5 rows x 26 columns],
 (5819079, 26))

In [9]:
deter_data.isnull().sum()

YEAR                   0
MONTH                  0
DAY                    0
DAY_OF_WEEK            0
FLIGHT_NUMBER          0
SCHEDULED_DEPARTURE    0
DEPARTURE_TIME         0
DEPARTURE_DELAY        0
TAXI_OUT               0
WHEELS_OFF             0
SCHEDULED_TIME         0
ELAPSED_TIME           0
AIR_TIME               0
DISTANCE               0
WHEELS_ON              0
TAXI_IN                0
SCHEDULED_ARRIVAL      0
ARRIVAL_TIME           0
ARRIVAL_DELAY          0
DIVERTED               0
CANCELLED              0
AIR_SYSTEM_DELAY       0
SECURITY_DELAY         0
AIRLINE_DELAY          0
LATE_AIRCRAFT_DELAY    0
WEATHER_DELAY          0
dtype: int64

In [10]:
# categorical features
categorical_features = [feature for feature in flights.columns if flights[feature].dtypes=='O']
print(categorical_features)

['AIRLINE', 'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT', 'CANCELLATION_REASON']

In [11]:
flights_cat = flights[categorical_features]
flights_cat.head()

  AIRLINE TAIL_NUMBER ORIGIN_AIRPORT DESTINATION_AIRPORT CANCELLATION_REASON
0      AS      N407AS            ANC                 SEA                 NaN
1      AA      N3KUAA            LAX                 PBI                 NaN
2      US      N171US            SFO                 CLT                 NaN
3      AA      N3HYAA            LAX                 MIA                 NaN
4      AS      N527AS            SEA                 ANC                 NaN

In [12]:
flights_cat.isnull().sum()

AIRLINE                      0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
CANCELLATION_REASON    5729195
dtype: int64

In [13]:
flights_final = deter_data.join(flights_cat)
flights_final.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,AIRLINE,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,CANCELLATION_REASON
0,2015.0,1.0,1.0,4.0,98.0,5.0,2354.0,-11.0,21.0,15.0,...,14.905347,0.066836,8.451934,16.999084,-0.217266,AS,N407AS,ANC,SEA,NaN
1,2015.0,1.0,1.0,4.0,2336.0,10.0,2.0,-8.0,12.0,14.0,...,10.782770,0.069328,11.761628,19.791908,1.310263,AA,N3KUAA,LAX,PBI,NaN
2,2015.0,1.0,1.0,4.0,840.0,20.0,18.0,-2.0,16.0,34.0,...,16.790757,0.077693,18.120679,15.549624,2.491187,US,N171US,SFO,CLT,NaN
3,2015.0,1.0,1.0,4.0,258.0,20.0,15.0,-5.0,15.0,30.0,...,14.706302,0.093863,21.061453,19.206171,2.814779,AA,N3HYAA,LAX,MIA,NaN
4,2015.0,1.0,1.0,4.0,135.0,25.0,24.0,-1.0,11.0,35.0,...,3.116763,0.020278,-8.213620,24.206035,-1.014899,AS,N527AS,SEA,ANC,NaN

In [14]:
for feature in categorical_features:
    print("Number of unique categories for",feature, "are",len(flights_final[feature].unique()),"out of",flights_final.shape[0])

Number of unique categories for AIRLINE are 14 out of 5819079
Number of unique categories for TAIL_NUMBER are 4898 out of 5819079
Number of unique categories for ORIGIN_AIRPORT are 930 out of 5819079
Number of unique categories for DESTINATION_AIRPORT are 930 out of 5819079
Number of unique categories for CANCELLATION_REASON are 5 out of 5819079

In [15]:
for feature in categorical_features:
    ordered_labels = flights_final.groupby([feature])['DEPARTURE_DELAY'].mean().sort_values().index
    ordered_labels = {k:i for i,k in enumerate(ordered_labels,0)}
    flights_final[feature] = flights_final[feature].map(ordered_labels)

In [16]:
flights_final.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,AIRLINE,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,CANCELLATION_REASON
0,2015.0,1.0,1.0,4.0,98.0,5.0,2354.0,-11.0,21.0,15.0,...,14.905347,0.066836,8.451934,16.999084,-0.217266,1,157.0,402,540,NaN
1,2015.0,1.0,1.0,4.0,2336.0,10.0,2.0,-8.0,12.0,14.0,...,10.782770,0.069328,11.761628,19.791908,1.310263,6,1454.0,808,845,NaN
2,2015.0,1.0,1.0,4.0,840.0,20.0,18.0,-2.0,16.0,34.0,...,16.790757,0.077693,18.120679,15.549624,2.491187,2,1423.0,821,481,NaN
3,2015.0,1.0,1.0,4.0,258.0,20.0,15.0,-5.0,15.0,30.0,...,14.706302,0.093863,21.061453,19.206171,2.814779,6,2521.0,808,756,NaN
4,2015.0,1.0,1.0,4.0,135.0,25.0,24.0,-1.0,11.0,35.0,...,3.116763,0.020278,-8.213620,24.206035,-1.014899,1,79.0,619,494,NaN

In [17]:
flights_final.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
FLIGHT_NUMBER                0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME               0
DEPARTURE_DELAY              0
TAXI_OUT                     0
WHEELS_OFF                   0
SCHEDULED_TIME               0
ELAPSED_TIME                 0
AIR_TIME                     0
DISTANCE                     0
WHEELS_ON                    0
TAXI_IN                      0
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME                 0
ARRIVAL_DELAY                0
DIVERTED                     0
CANCELLED                    0
AIR_SYSTEM_DELAY             0
SECURITY_DELAY               0
AIRLINE_DELAY                0
LATE_AIRCRAFT_DELAY          0
WEATHER_DELAY                0
AIRLINE                      0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
CANCELLATION_REASON    5729195
dtype: int64

In [18]:
missing_columns = flights_final[flights_final.columns[26:31]]            

for feature in missing_columns:
    flights_final[feature + '_imp'] = flights_final[feature]
    flights_final = random_imputation(flights_final, feature)

In [19]:
final_data = pd.DataFrame(columns = [name for name in missing_columns])

for feature in missing_columns:
        
    final_data[feature] = flights_final[feature + "_imp"]
    parameters = list(set(flights_final.columns) - set(missing_columns) - {feature + '_imp'})
    
    #Create a Linear Regression ridge model to estimate the missing data
    model = linear_model.Ridge()
    model.fit(X = flights_final[parameters], y = flights_final[feature + '_imp'])
    
    #preserve the index of the missing data from the original dataframe
    final_data.loc[flights_final[feature].isnull(), feature] = model.predict(flights_final[parameters])[flights_final[feature].isnull()]

In [20]:
final_data.head()

,AIRLINE,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,CANCELLATION_REASON
0,1.0,157.0,402.0,540.0,2.378153
1,6.0,1454.0,808.0,845.0,2.372740
2,2.0,1423.0,821.0,481.0,2.375763
3,6.0,2521.0,808.0,756.0,2.376500
4,1.0,79.0,619.0,494.0,2.374055

In [21]:
flights_final_data = deter_data.join(final_data)
flights_final_data.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,AIRLINE,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,CANCELLATION_REASON
0,2015.0,1.0,1.0,4.0,98.0,5.0,2354.0,-11.0,21.0,15.0,...,14.905347,0.066836,8.451934,16.999084,-0.217266,1.0,157.0,402.0,540.0,2.378153
1,2015.0,1.0,1.0,4.0,2336.0,10.0,2.0,-8.0,12.0,14.0,...,10.782770,0.069328,11.761628,19.791908,1.310263,6.0,1454.0,808.0,845.0,2.372740
2,2015.0,1.0,1.0,4.0,840.0,20.0,18.0,-2.0,16.0,34.0,...,16.790757,0.077693,18.120679,15.549624,2.491187,2.0,1423.0,821.0,481.0,2.375763
3,2015.0,1.0,1.0,4.0,258.0,20.0,15.0,-5.0,15.0,30.0,...,14.706302,0.093863,21.061453,19.206171,2.814779,6.0,2521.0,808.0,756.0,2.376500
4,2015.0,1.0,1.0,4.0,135.0,25.0,24.0,-1.0,11.0,35.0,...,3.116763,0.020278,-8.213620,24.206035,-1.014899,1.0,79.0,619.0,494.0,2.374055

In [28]:
flights_final_data.tail()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,AIRLINE,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,CANCELLATION_REASON
5819074,2015.0,12.0,31.0,4.0,688.0,2359.0,2355.0,-4.0,22.0,17.0,...,9.831881,0.098272,12.417222,24.936181,3.033297,10.0,4157.0,811.0,816.0,2.360470
5819075,2015.0,12.0,31.0,4.0,745.0,2359.0,2355.0,-4.0,17.0,12.0,...,8.392745,0.082872,10.186068,23.910808,2.375310,10.0,3683.0,843.0,873.0,2.352067
5819076,2015.0,12.0,31.0,4.0,1503.0,2359.0,2350.0,-9.0,17.0,7.0,...,13.625203,0.099997,14.680705,23.926305,3.679788,10.0,4396.0,843.0,828.0,2.349452
5819077,2015.0,12.0,31.0,4.0,333.0,2359.0,2353.0,-6.0,10.0,3.0,...,9.868588,0.087790,10.763320,22.902839,3.026942,10.0,3856.0,837.0,828.0,2.350840
5819078,2015.0,12.0,31.0,4.0,839.0,2359.0,14.0,15.0,14.0,28.0,...,10.317292,0.112071,32.275205,32.363626,7.771272,10.0,3921.0,843.0,892.0,2.346242

In [29]:
flights_final_data.describe()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,AIRLINE,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,CANCELLATION_REASON
count,5819079.0,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,...,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06
mean,2015.0,6.524085e+00,1.570459e+01,3.926941e+00,2.173093e+03,1.329602e+03,1.335222e+03,9.394247e+00,1.607359e+01,1.357152e+03,...,1.275926e+01,7.478302e-02,1.680832e+01,2.181574e+01,2.484560e+00,6.581479e+00,2.207722e+03,7.226488e+02,6.983988e+02,2.367949e+00
std,0.0,3.405137e+00,8.783425e+00,1.988845e+00,1.757064e+03,4.837518e+02,4.945218e+02,3.726495e+01,9.399248e+00,4.965553e+02,...,1.228759e+01,9.164237e-01,2.112533e+01,1.890539e+01,8.778958e+00,3.278257e+00,1.266619e+03,1.390572e+02,1.407143e+02,9.509274e-02
min,2015.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-1.461451e+02,-2.965951e+02,1.000000e+00,...,-7.623060e+01,-3.296468e-01,-7.805980e+01,-9.324045e+01,-2.169760e+01,0.000000e+00,-2.919415e+02,0.000000e+00,0.000000e+00,0.000000e+00
25%,2015.0,4.000000e+00,8.000000e+00,2.000000e+00,7.300000e+02,9.170000e+02,9.230000e+02,-5.000000e+00,1.100000e+01,9.370000e+02,...,1.000146e+01,5.483852e-02,1.233113e+01,1.853545e+01,1.380793e+00,4.000000e+00,1.134000e+03,6.660000e+02,6.460000e+02,2.365844e+00
50%,2015.0,7.000000e+00,1.600000e+01,4.000000e+00,1.690000e+03,1.325000e+03,1.330000e+03,-2.000000e+00,1.400000e+01,1.343000e+03,...,1.207381e+01,7.339369e-02,1.627860e+01,2.159186e+01,2.331702e+00,6.000000e+00,2.195000e+03,7.510000e+02,7.340000e+02,2.368127e+00
75%,2015.0,9.000000e+00,2.300000e+01,6.000000e+00,3.230000e+03,1.730000e+03,1.738000e+03,8.000000e+00,1.900000e+01,1.753000e+03,...,1.433906e+01,8.213382e-02,1.920343e+01,2.364086e+01,2.827960e+00,9.000000e+00,3.247000e+03,8.270000e+02,8.010000e+02,2.370319e+00
max,2015.0,1.200000e+01,3.100000e+01,7.000000e+00,9.855000e+03,2.359000e+03,2.422193e+03,1.988000e+03,4.168051e+02,2.400000e+03,...,1.134000e+03,5.730000e+02,1.971000e+03,1.331000e+03,1.211000e+03,1.300000e+01,4.896000e+03,9.290000e+02,9.290000e+02,3.000000e+00

In [22]:
flights_final_data['AIR_TIME']=np.where(flights_final_data['AIR_TIME']<0,7.0,flights_final_data['AIR_TIME'])
flights_final_data['ELAPSED_TIME']=np.where(flights_final_data['ELAPSED_TIME']<0,14.0,flights_final_data['ELAPSED_TIME'])
flights_final_data['TAXI_IN']=np.where(flights_final_data['TAXI_IN']==0,1.0,flights_final_data['TAXI_IN'])
flights_final_data['TAXI_OUT']=np.where(flights_final_data['TAXI_OUT']==0,1.0,flights_final_data['TAXI_OUT'])

In [23]:
flights_final_data.describe()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,AIRLINE,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,CANCELLATION_REASON
count,5819079.0,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,...,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06
mean,2015.0,6.524085e+00,1.570459e+01,3.926941e+00,2.173093e+03,1.329602e+03,1.335276e+03,9.396742e+00,1.607280e+01,1.357176e+03,...,1.272562e+01,7.446861e-02,1.681165e+01,2.178643e+01,2.479101e+00,6.581479e+00,2.206424e+03,7.228874e+02,6.994718e+02,2.368116e+00
std,0.0,3.405137e+00,8.783425e+00,1.988845e+00,1.757064e+03,4.837518e+02,4.945142e+02,3.727193e+01,9.401371e+00,4.965443e+02,...,1.228817e+01,9.164183e-01,2.112458e+01,1.890506e+01,8.779285e+00,3.278257e+00,1.267071e+03,1.384314e+02,1.397427e+02,9.509959e-02
min,2015.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-1.659306e+02,-3.147439e+02,1.000000e+00,...,-8.138773e+01,-2.750616e-01,-8.373021e+01,-9.366558e+01,-2.376807e+01,0.000000e+00,-3.025962e+02,0.000000e+00,0.000000e+00,0.000000e+00
25%,2015.0,4.000000e+00,8.000000e+00,2.000000e+00,7.300000e+02,9.170000e+02,9.230000e+02,-5.000000e+00,1.100000e+01,9.370000e+02,...,9.980191e+00,5.414985e-02,1.234295e+01,1.850665e+01,1.365456e+00,4.000000e+00,1.134000e+03,6.670000e+02,6.460000e+02,2.365656e+00
50%,2015.0,7.000000e+00,1.600000e+01,4.000000e+00,1.690000e+03,1.325000e+03,1.330000e+03,-2.000000e+00,1.400000e+01,1.343000e+03,...,1.202576e+01,7.263606e-02,1.628684e+01,2.155039e+01,2.319206e+00,6.000000e+00,2.196000e+03,7.520000e+02,7.400000e+02,2.368124e+00
75%,2015.0,9.000000e+00,2.300000e+01,6.000000e+00,3.230000e+03,1.730000e+03,1.738000e+03,8.000000e+00,1.900000e+01,1.753000e+03,...,1.430127e+01,8.196024e-02,1.920095e+01,2.360067e+01,2.827394e+00,9.000000e+00,3.249000e+03,8.280000e+02,7.970000e+02,2.370574e+00
max,2015.0,1.200000e+01,3.100000e+01,7.000000e+00,9.855000e+03,2.359000e+03,2.400000e+03,1.988000e+03,2.983473e+02,2.400000e+03,...,1.134000e+03,5.730000e+02,1.971000e+03,1.331000e+03,1.211000e+03,1.300000e+01,4.896000e+03,9.290000e+02,9.290000e+02,3.000000e+00

In [24]:
numerical_features_encoding = ['MONTH','DAY','DAY_OF_WEEK','FLIGHT_NUMBER']

In [25]:
for feature in numerical_features_encoding:
    print("Number of unique features for", feature, "are",len(flights_final_data[feature].unique()),"out of",flights_final_data.shape[0])

Number of unique features for MONTH are 12 out of 5819079
Number of unique features for DAY are 31 out of 5819079
Number of unique features for DAY_OF_WEEK are 7 out of 5819079
Number of unique features for FLIGHT_NUMBER are 6952 out of 5819079

In [26]:
for feature in numerical_features_encoding:
    ordered_labels=flights_final_data.groupby([feature])['DEPARTURE_DELAY'].mean().sort_values().index
    ordered_labels = {k:i for i, k in enumerate(ordered_labels, 0)}
    flights_final_data[feature]= flights_final_data[feature].map(ordered_labels)

In [35]:
flights_final_data.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,AIRLINE,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,CANCELLATION_REASON
0,2015.0,6,26,5,4854,5.0,2354.0,-11.0,21.0,15.0,...,14.946822,0.085513,9.538784,17.414271,0.033101,1.0,161.0,401.0,540.0,2.381220
1,2015.0,6,26,5,3750,10.0,2.0,-8.0,12.0,14.0,...,12.668895,0.073640,17.155908,17.443082,2.489191,6.0,1447.0,811.0,844.0,2.371965
2,2015.0,6,26,5,2039,20.0,18.0,-2.0,16.0,34.0,...,17.300664,0.082108,21.081782,19.596594,3.105542,2.0,1417.0,823.0,477.0,2.373709
3,2015.0,6,26,5,1747,20.0,15.0,-5.0,15.0,30.0,...,8.890133,0.025558,-1.453738,18.556058,-0.644034,6.0,2519.0,811.0,754.0,2.376581
4,2015.0,6,26,5,6086,25.0,24.0,-1.0,11.0,35.0,...,11.054393,0.080846,21.041308,20.699611,3.061891,1.0,81.0,616.0,496.0,2.371794

In [27]:
flights_final_data = flights_final_data.drop(['YEAR','DAY_OF_WEEK','ORIGIN_AIRPORT','DESTINATION_AIRPORT','TAIL_NUMBER','WHEELS_OFF','DISTANCE','DEPARTURE_TIME','ELAPSED_TIME','AIR_TIME','ARRIVAL_TIME','DIVERTED','MONTH','DAY','SCHEDULED_ARRIVAL'],axis=1)

In [28]:
cormatrix = flights_final_data.corr()
cormatrix

,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_DELAY,TAXI_OUT,SCHEDULED_TIME,WHEELS_ON,TAXI_IN,ARRIVAL_DELAY,CANCELLED,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,AIRLINE,CANCELLATION_REASON
FLIGHT_NUMBER,1.000000,0.172841,0.085466,0.026794,0.104405,0.148053,0.027650,0.068322,0.005497,0.006093,-0.000443,-0.000111,0.032154,0.002068,0.139365,0.007504
SCHEDULED_DEPARTURE,0.172841,1.000000,0.107150,0.005405,-0.016609,0.648348,-0.042781,0.098226,0.011752,-0.058106,-0.004905,-0.088238,0.072197,-0.025056,0.006180,-0.009083
DEPARTURE_DELAY,0.085466,0.107150,1.000000,0.069051,0.035402,0.057290,0.022648,0.910987,0.012403,0.083997,0.010502,0.521023,0.467564,0.209637,0.072397,0.014903
TAXI_OUT,0.026794,0.005405,0.069051,1.000000,0.108066,0.030919,0.106735,0.189362,0.001431,0.336475,-0.006028,-0.069984,-0.123398,0.057525,-0.091981,-0.006704
SCHEDULED_TIME,0.104405,-0.016609,0.035402,0.108066,1.000000,0.023099,0.096559,-0.039762,-0.027826,0.017205,0.005967,0.024309,-0.032931,-0.003778,0.127749,0.018954
WHEELS_ON,0.148053,0.648348,0.057290,0.030919,0.023099,1.000000,-0.003086,0.057224,0.000468,-0.009430,-0.005661,-0.068617,0.000704,-0.027687,-0.014819,0.006225
TAXI_IN,0.027650,-0.042781,0.022648,0.106735,0.096559,-0.003086,1.000000,0.086590,0.001127,0.232983,-0.005671,-0.051773,-0.058221,-0.003975,0.024119,-0.002755
ARRIVAL_DELAY,0.068322,0.098226,0.910987,0.189362,-0.039762,0.057224,0.086590,1.000000,0.000209,0.215248,0.006953,0.454101,0.387797,0.207226,0.041662,-0.004251
CANCELLED,0.005497,0.011752,0.012403,0.001431,-0.027826,0.000468,0.001127,0.000209,1.000000,0.005779,0.000592,0.013057,0.011844,0.007418,0.013898,-0.000435
AIR_SYSTEM_DELAY,0.006093,-0.058106,0.083997,0.336475,0.017205,-0.009430,0.232983,0.215248,0.005779,1.000000,-0.010424,-0.117284,-0.149648,0.008178,-0.007263,-0.004319
SECURITY_DELAY,-0.000443,-0.004905,0.010502,-0.006028,0.005967,-0.005661,-0.005671,0.006953,0.000592,-0.010424,1.000000,-0.010159,-0.009245,-0.003715,0.000091,0.001989
AIRLINE_DELAY,-0.000111,-0.088238,0.521023,-0.069984,0.024309,-0.068617,-0.051773,0.454101,0.013057,-0.117284,-0.010159,1.000000,-0.075045,-0.035066,0.010597,0.005787
LATE_AIRCRAFT_DELAY,0.032154,0.072197,0.467564,-0.123398,-0.032931,0.000704,-0.058221,0.387797,0.011844,-0.149648,-0.009245,-0.075045,1.000000,-0.007221,0.037595,0.006219
WEATHER_DELAY,0.002068,-0.025056,0.209637,0.057525,-0.003778,-0.027687,-0.003975,0.207226,0.007418,0.008178,-0.003715,-0.035066,-0.007221,1.000000,-0.001478,-0.002990
AIRLINE,0.139365,0.006180,0.072397,-0.091981,0.127749,-0.014819,0.024119,0.041662,0.013898,-0.007263,0.000091,0.010597,0.037595,-0.001478,1.000000,0.011208
CANCELLATION_REASON,0.007504,-0.009083,0.014903,-0.006704,0.018954,0.006225,-0.002755,-0.004251,-0.000435,-0.004319,0.001989,0.005787,0.006219,-0.002990,0.011208,1.000000

In [29]:
flights_sample1= flights_final_data.sample(n=1000000).copy()
from sklearn.model_selection import train_test_split
Y = flights_sample1.DEPARTURE_DELAY
X = flights_sample1.drop('DEPARTURE_DELAY',axis = 1)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

In [30]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((700000, 15), (300000, 15), (700000,), (300000,))

In [31]:
# linar regression model
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
L_model= lm.fit(X_train,Y_train)
predictions= lm.predict(X_test)
predictions[0:10]

array([ 15.3318692 ,  16.0833162 ,   2.56876125,  21.96142617,
       -21.88713336,   2.03817018,  20.32473884, -10.03671881,
        -2.15308042, 177.65559017])

In [32]:
Y_test.head(10)

4602000     33.0
3098568     18.0
2432556      5.0
1642074     20.0
4607426    -22.0
3630346     -5.0
1565378     21.0
4110415     -7.0
5616230     -3.0
1565382    185.0
Name: DEPARTURE_DELAY, dtype: float64

In [33]:
from sklearn import metrics
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, predictions)))
print('Mean Squared error:', (metrics.mean_squared_error(Y_test,predictions)).mean())
print('Mean Absolute Error:', (metrics.mean_absolute_error(Y_test,predictions)))
print('R2 value:', (metrics.r2_score(Y_test,predictions)))

Root Mean Squared Error: 12.387474583899435
Mean Squared error: 153.44952656675449
Mean Absolute Error: 6.941366152164804
R2 value: 0.8892021656022496

In [34]:
print('Accuracy score:',L_model.score(X_test,Y_test)*100)

Accuracy score: 88.92021656022496

In [35]:
# Random forest
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr_model = rfr.fit(X_train,Y_train)
Y_predicted = rfr_model.predict(X_test)

In [36]:
Y_predicted[0:10],Y_test.head(10)

(array([ 27.36,  18.  ,   1.71,  20.54, -28.46,  -4.04,  18.57,  -6.5 ,
         -3.86, 186.86]),
 4602000     33.0
 3098568     18.0
 2432556      5.0
 1642074     20.0
 4607426    -22.0
 3630346     -5.0
 1565378     21.0
 4110415     -7.0
 5616230     -3.0
 1565382    185.0
 Name: DEPARTURE_DELAY, dtype: float64)

In [37]:
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, Y_predicted)))
print('Mean Squared error:', (metrics.mean_squared_error(Y_test,Y_predicted)).mean())
print('Mean Absolute Error:', (metrics.mean_absolute_error(Y_test,Y_predicted)))
print('R2 value:', (metrics.r2_score(Y_test,Y_predicted)))

Root Mean Squared Error: 4.647950294314512
Mean Squared error: 21.60344193841836
Mean Absolute Error: 2.2919507777053507
R2 value: 0.9844012905359274

In [38]:
print('Accuracy score:',rfr_model.score(X_test,Y_test)*100)

Accuracy score: 98.44012905359274

In [39]:
print(pd.DataFrame(rfr_model.feature_importances_, index=X_train.columns, columns=['feature importance']).sort_values('feature importance', ascending=False))

                     feature importance
ARRIVAL_DELAY                  0.804227
AIR_SYSTEM_DELAY               0.110860
LATE_AIRCRAFT_DELAY            0.028783
TAXI_OUT                       0.013073
CANCELLATION_REASON            0.012500
CANCELLED                      0.010098
AIRLINE_DELAY                  0.004756
TAXI_IN                        0.003399
SCHEDULED_TIME                 0.002840
WEATHER_DELAY                  0.002217
SECURITY_DELAY                 0.001990
WHEELS_ON                      0.001615
SCHEDULED_DEPARTURE            0.001342
AIRLINE                        0.001218
FLIGHT_NUMBER                  0.001081

In [41]:
import pickle
pickle.dump(rfr_model, open('model.pkl','wb'))